n_orig: 30
d_mul: 4  # number of constraints will equal d_mul * n_orig
x_var: .1  # variance in the Gaussians for X
x_mean: 0 #5
###### change the above for phase_retrieval

solve_acc_abs: 1e-2
solve_acc_rel: 0
solve_max_iters: 1000
N_train: 100
N_test: 20
seed: 42
solve: True
