n_orig: 40
d_mul: 10  # number of constraints will equal d_mul * n_orig
x_var: 1  # variance in the Gaussians for X
x_mean: 0 #5
###### change the above for phase_retrieval

solve_acc_abs: 1e-4
solve_acc_rel: 0
N_train: 100
N_test: 20
seed: 42
solve: True
