nn_cfg:
  lr: 1e-3 #1e-2
  method: adam
  intermediate_layer_sizes: [500, 500]
  batch_size: 100
  epochs: 1e6
  decay_lr: .1
  min_lr: 1e-7
  decay_every: 1e7

plateau_decay:
  min_lr: 1e-7
  decay_factor: 5
  avg_window_size: 5 # in epochs
  tolerance: 1e-3
  patience: 1


pretrain:
  pretrain_method: adam
  pretrain_stepsize: 1e-3
  pretrain_iters: 0
  pretrain_batches: 10

data:
  datetime: ''

train_unrolls: 5  # this is the k that tells you how many FOM iterations
eval_unrolls: 1000
eval_every_x_epochs: 5
save_every_x_epochs: 1
test_every_x_epochs: 1
write_csv_every_x_batches: 1
N_train: 3000  # adjust these for larger setups
N_test: 100
num_samples: 100
prediction_variable: w
angle_anchors: [0]
supervised: True
plot_iterates: [0, 10, 100]
loss_method: 'fixed_k' #'fixed_k' #'constant_sum'
share_all: False  # this is the shared solution approach
num_clusters: 1000
pretrain_alpha: False
normalize_inputs: True
normalize_alpha: 'other'
epochs_jit: 2
accuracies: [1, .1, .01, .001, .0001]

rho_x: 1
scale: 1
alpha_relax: 1
skip_startup: False  # can be used to skip the eval for no learn and NN 
# solve_c_num: 50
save_weights_flag: True