nn_cfg:
  lr: 1e-3
  method: adam
  intermediate_layer_sizes: [500, 500]
  batch_size: 100
  epochs: 1e6
  decay_lr: .1
  min_lr: 1e-7
  decay_every: 1e7

plateau_decay:
  min_lr: 1e-7
  decay_factor: 5
  avg_window_size: 5 # in epochs
  tolerance: 1e-3
  patience: 1


pretrain:
  pretrain_method: adam
  pretrain_stepsize: 1e-3
  pretrain_iters: 0
  pretrain_batches: 10

data:
  datetime: ''


eval_unrolls: 300
eval_every_x_epochs: 10
save_every_x_epochs: 1
test_every_x_epochs: 1
write_csv_every_x_batches: 1
N_train: 45000
N_test: 1000
num_samples: 100
prediction_variable: w
angle_anchors: [0]
plot_iterates: [0, 10, 20]
loss_method: 'fixed_k' #'fixed_k' #'constant_sum'
share_all: False
num_clusters: 1000
pretrain_alpha: False
normalize_inputs: True
normalize_alpha: 'other'
epochs_jit: 2
accuracies: [.1, .01, .001, .0001]

rho_x: 1
scale: 1
alpha_relax: 1
skip_startup: False
# solve_c_num: 1000
# save_weights_flag: False
# load_weights_datetime: '2023-07-20/15-22-02' #'2023-08-02/10-19-58'
train_unrolls: 15
supervised: True
lightweight: True

# obj: output_datetimes: ['2023-05-24/16-12-32', '2023-05-24/16-13-32', '2023-05-24/16-16-56', '2023-05-24/16-17-35', '2023-05-24/16-18-05', 
# reg: '2023-06-15/20-58-39', '2023-06-15/20-56-15', '2023-06-15/21-24-04', '2023-07-11/21-07-41', '2023-07-11/21-08-43']

save_weights_flag: True
load_weights_datetime: '2024-01-07/12-24-24'
nn_load_type: stochastic

pac_bayes_cfg:
  init_var: 1e-3
  c: 10.0
  b: 100
  delta: 0.01
  rep: True
  penalty_coeff: 0.5
  deterministic: False