nn_cfg:
  lr: 1e-4
  method: adam
  intermediate_layer_sizes: [500, 500]
  batch_size: 100
  epochs: 300
  decay_lr: .6
  min_lr: 1e-7
  decay_every: 1000

pretrain:
  pretrain_method: adam
  pretrain_stepsize: 1e-4
  pretrain_iters: 3000
  pretrain_batches: 10

data:
  datetime: ''

train_unrolls: 30
eval_unrolls: 500
eval_every_x_epochs: 10
save_every_x_epochs: 2
write_csv_every_x_batches: 10
N_train: 200
N_test: 20
num_samples: 20
prediction_variable: w
supervised: False
angle_anchors: [0]
dx: 34
dy: 34
tx: 10
ty: 10