nn_cfg:
  lr: 1e-3
  method: adam
  intermediate_layer_sizes: [500, 500]
  batch_size: 100
  epochs: 100000
  decay_lr: .6
  min_lr: 1e-7
  decay_every: 1000

pretrain:
  pretrain_method: adam
  pretrain_stepsize: 1e-4
  pretrain_iters: 0
  pretrain_batches: 10

data:
  datetime: ''

train_unrolls: 20
eval_unrolls: 500
eval_every_x_epochs: 10
save_every_x_epochs: 1
write_csv_every_x_batches: 1
N_train: 100
N_test: 20
num_samples: 100
prediction_variable: w
supervised: False
angle_anchors: [0]
dx: 0
dy: 0
tx: 20
ty: 20
learn_XY: False
num_clusters: 20
loss_method: constant_sum
#increasing_sum or constant_sum or fixed_k 
plot_iterates: [10]
share_all: True