nn_cfg:
  lr: 1e-3
  method: adam
  intermediate_layer_sizes: [500, 500]
  batch_size: 10
  epochs: 300
  decay_lr: .6
  min_lr: 1e-7
  decay_every: 1000

pretrain:
  pretrain_method: adam
  pretrain_stepsize: .001
  pretrain_iters: 0

data:
  datetime: ''

train_unrolls: 10
eval_unrolls: 500
eval_every_x_epochs: 10
N_train: 100
N_test: 20
num_samples: 20
prediction_variable: w
supervised: False
angle_anchors: [0]
dx: 5
dy: 6
tx: 20
ty: 20