eval_iters: 500
# datetimes: ''
# datetimes: ['2023-01-19/23-07-45', '2023-01-19/21-26-18']

# below is the best run for meeting jan 25
# datetimes: ['2023-01-20/23-08-01', '2023-01-22/22-42-59', '2023-01-20/19-13-45']
datetimes: '' #['2023-01-19/22-45-22', '2023-01-20/09-14-51']
labels: ['custom title'] #['incr. loss sum to k', 'const. loss sum to k', 'loss only at k']
add_k: True
# y_low: 3e-5
# y_high: 5e1
gif_length: 3
gradient: True
# y_grad_low: 8e-4
# y_grad_high: 3e1
angle_prob_nums: [0, 1]