solve_acc_abs: 1e-3
solve_acc_rel: 0
lambd: .001
lambd2: 0.4
N_train: 100
N_test: 100
seed: 42
solve: True
noise_std_dev: .001
blur_size: 8
dataset: emnist
obj_const: 10
A_scale: 1
deblur_or_denoise: 'deblur'
mri_size: 70
# salt_and_pepper_noise_prob: 0.2
