nn_cfg:
  lr: 1e-3
  method: adam
  intermediate_layer_sizes: [500, 500]
  batch_size: 100
  epochs: 1e6
  decay_lr: .1
  min_lr: 1e-7
  decay_every: 1e7

plateau_decay:
  min_lr: 1e-7
  decay_factor: 5
  avg_window_size: 5 # in epochs
  tolerance: 1e-3
  patience: 50


pretrain:
  pretrain_method: adam
  pretrain_stepsize: 1e-3
  pretrain_iters: 0
  pretrain_batches: 10

data:
  datetime: '' #'2023-04-10/11-17-04'

train_unrolls: 5
eval_unrolls: 500
eval_every_x_epochs: 1
save_every_x_epochs: 1
test_every_x_epochs: 1
write_csv_every_x_batches: 1
epochs_jit: 2
N_train: 10000
N_test: 100
num_samples: 20
prediction_variable: w
angle_anchors: [0]
supervised: True
plot_iterates: [0, 10, 20]
loss_method: 'fixed_k' #'fixed_k' #'constant_sum'
share_all: False
num_clusters: 100
pretrain_alpha: False
normalize_inputs: True
normalize_alpha: 'other'

accuracies: [1, .1, .01, .001, .0001]
rho_x: 1
scale: 1
alpha_relax: 1
skip_startup: True
# solve_c_num: 10
save_weights_flag: True
# load_weights_datetime: '2023-06-05/13-51-16'