nn_cfg:
  lr: 1e-4
  method: adam
  intermediate_layer_sizes: [500, 2000]
  batch_size: 100
  epochs: 1e6
  decay_lr: .1
  min_lr: 1e-7
  decay_every: 1e7

plateau_decay:
  min_lr: 1e-7
  decay_factor: 5
  avg_window_size: 5 # in epochs
  tolerance: 1e-3
  patience: 50


pretrain:
  pretrain_method: adam
  pretrain_stepsize: 1e-3
  pretrain_iters: 0
  pretrain_batches: 10

data:
  datetime: '' #'2023-04-10/11-17-04'

train_unrolls: 15
<<<<<<< HEAD
eval_unrolls: 1500
=======
eval_unrolls: 1000
>>>>>>> f04eab0a096914696a5ced9e86e8c0f1c069635f
eval_every_x_epochs: 5
save_every_x_epochs: 1
test_every_x_epochs: 1
write_csv_every_x_batches: 1
<<<<<<< HEAD
N_train: 10
=======
epochs_jit: 2
N_train: 10000
>>>>>>> f04eab0a096914696a5ced9e86e8c0f1c069635f
N_test: 50
num_samples: 50
prediction_variable: w
angle_anchors: [0]
supervised: False
plot_iterates: [0, 10, 20]
loss_method: 'fixed_k' #'fixed_k' #'constant_sum'
share_all: False
num_clusters: 100
pretrain_alpha: False
normalize_inputs: True
normalize_alpha: 'other'

accuracies: [.1, .01, .001, .0001]
rho_x: 1
scale: 1
alpha_relax: 1
skip_startup: False