nx: 20
nu: 10
T: 10
traj_length: 10
x_init_factor: .5
solve_acc_abs: 1e-4
solve_acc_rel: 0
N_train: 1000
N_test: 100
seed: 42
solve: True
<<<<<<< HEAD
noise_std_dev: 0.0
=======
noise_std_dev: 0.1
>>>>>>> e0e5dae175583fad344e5ec78e2a05afacef884b
