solve_acc_abs: 1e-3
solve_acc_rel: 0
lambd: 1e-4
N_train: 5000
N_test: 1000
seed: 42
solve: True
noise_std_dev: 0
blur_size: 5
dataset: mri
obj_const: 1
A_scale: 1
deblur_or_denoise: 'deblur'
mri_size: 50
