solve_acc_abs: 1e-3
solve_acc_rel: 0
lambd: 0.2
lambd2: 0.4
N_train: 10000
N_test: 100
seed: 42
solve: True
noise_std_dev: .25
blur_size: 1
dataset: emnist
obj_const: 1
A_scale: 1
deblur_or_denoise: 'denoise'
mri_size: 70
