nn_cfg:
  lr: 1e-3
  method: adam
  intermediate_layer_sizes: [500, 500]
  batch_size: 100
  epochs: 1e6
  decay_lr: .1
  min_lr: 1e-7
  decay_every: 1e7

plateau_decay:
  min_lr: 1e-7
  decay_factor: 5
  avg_window_size: 5000 # in epochs
  tolerance: -100 #1e-3
  patience: 1


pretrain:
  pretrain_method: adam
  pretrain_stepsize: 1e-3
  pretrain_iters: 0
  pretrain_batches: 10

data:
  datetime: ''

train_unrolls: 5
eval_unrolls: 200
eval_every_x_epochs: 20
save_every_x_epochs: 1
test_every_x_epochs: 1
write_csv_every_x_batches: 1
epochs_jit: 2
N_train: 10000
N_test: 100
num_samples: 100
prediction_variable: w
angle_anchors: [0]
supervised: True
plot_iterates: [0, 10, 20]
loss_method: 'fixed_k' #'fixed_k' #'constant_sum'
share_all: False
num_clusters: 10
pretrain_alpha: False
normalize_inputs: True
normalize_alpha: 'other'

accuracies: [.1, .01, .001, .0001]
rho_x: 1
scale: 1
alpha_relax: 1
skip_startup: False

sigma_nn: [0.0, 1e-6, 1e-5, 0.0001, 0.001, 0.01, .1, 1, 10]
pac_bayes_num_samples: 5
pac_bayes_flag: False


save_weights_flag: True
# load_weights_datetime: '2024-01-07/22-42-52'
# nn_load_type: deterministic

pac_bayes_cfg:
  init_var: 1e-4
  c: 10.0
  b: 100
  delta: 0.01
  rep: True
  penalty_coeff: 1.0
  deterministic: False