nn_cfg:
  lr: 1e-3
  method: adam
  intermediate_layer_sizes: [1000, 1000]
  batch_size: 100
  epochs: 1e6
  decay_lr: .1
  min_lr: 1e-7
  decay_every: 1e7

plateau_decay:
  min_lr: 1e-7
  decay_factor: 5
  avg_window_size: 10 # in epochs
  tolerance: 1e-4
  patience: 2


pretrain:
  pretrain_method: adam
  pretrain_stepsize: 1e-3
  pretrain_iters: 0
  pretrain_batches: 10

data:
  datetime: ''

train_unrolls: 120
eval_unrolls: 500
eval_every_x_epochs: 20
save_every_x_epochs: 1
test_every_x_epochs: 1
write_csv_every_x_batches: 1
N_train: 10000
N_test: 1000
num_samples: 100
angle_anchors: [0]
supervised: False
plot_iterates: [0, 10, 20]
loss_method: 'fixed_k' #'fixed_k' #'constant_sum'
share_all: False
num_clusters: 2000
pretrain_alpha: False
normalize_inputs: True
normalize_alpha: 'other'
epochs_jit: 10
accuracies: [1, .1, .01, .001, .0001]
iterates_visualize: [10]

rho_x: 1
scale: 1
alpha_relax: 1
skip_startup: True

solve_c_num: 100
save_weights_flag: True
# load_weights_datetime: '2023-05-22/16-43-06'
#5: '2023-05-22/14-22-20'
#15: '2023-05-22/14-23-18'
#30: '2023-05-22/15-25-55'
#60: '2023-05-22/15-29-14'
#120: '2023-05-22/16-37-55'
#1: '2023-05-22/16-43-06'