T: 10
dt: 0.04
rollout_length: 100
waypoints: 10 #10
rollout_osqp_iters: 500
num_rollouts: 110
R_diag:
- 0.01
- 0.01
- 0.01
- 0.01
Q_diag:
- 20
- 20
- 20
- 0
- 0
- 0
- 0
- 0
- 0
- 0
QT_factor: 1
obstacle_tol: 0.1
goal_bound: .5 #.5
num_goals: 5
solve_acc_abs: 0.0001
solve_acc_rel: 0
x_min:
- -2
- -2
- -2
- -50
- -50
- -50
- -2
- -2
- -2
- -2
x_max:
- 2
- 2
- 2
- 50
- 50
- 50
- 2
- 2
- 2
- 2
u_min:
- 2
- -6
- -6
- -6
u_max:
- 20
- 6
- 6
- 6
delta_u:
- 20
- 6
- 6
- 6
seed: 42
solve: true
noise_std_dev: 0
save_gif: true
