nn_cfg:
  lr: 0.0001
  method: adam
  intermediate_layer_sizes:
  - 100
  - 500
  batch_size: 100
  epochs: 1000000.0
  decay_lr: 0.1
  min_lr: 1.0e-07
  decay_every: 10000000.0
plateau_decay:
  min_lr: 1.0e-07
  decay_factor: 5
  avg_window_size: 5
  tolerance: 1.0e-08
  patience: 1
pretrain:
  pretrain_method: adam
  pretrain_stepsize: 0.001
  pretrain_iters: 0
  pretrain_batches: 10
data:
  datetime: ''
train_unrolls: 5
eval_unrolls: 100
eval_every_x_epochs: 200
save_every_x_epochs: 1
test_every_x_epochs: 1
write_csv_every_x_batches: 1
epochs_jit: 10
N_train: 10000
N_test: 1000
num_samples: 100
prediction_variable: w
angle_anchors:
- 0
supervised: true
plot_iterates:
- 0
- 10
- 20
loss_method: fixed_k
num_clusters: 10
pretrain_alpha: false
normalize_inputs: true
normalize_alpha: other
accuracies:
- 0.1
- 0.01
- 0.001
- 0.0001
rho_x: 1
scale: 1
alpha_relax: 1
skip_startup: true
save_weights_flag: true
load_weights_datetime: 2023-07-09/14-14-53
num_rollouts: 5
closed_loop_budget: 15
