T: 20
dt: .02
rollout_length: 5
rollout_osqp_iters: 500
num_rollouts: 2
R_diag: [.1, .1, .1, .1]
Q_diag: [1, 1, 1, 1, 1, 1, 0, 0, 0, .01, .01, .01]
QT_factor: 1
obstacle_tol: .05
goal_bound: 3
num_goals: 5
solve_acc_abs: 1e-4
solve_acc_rel: 0
x_min: [-10, -10, -10, -10, -10, -10, -1, -1, -1, -10, -10, -10]
x_max: [10, 10, 10, 10, 10, 10, 1, 1, 1, 10, 10, 10]
u_min: [0, 0, 0, 0]
u_max: [10, 10, 10, 10]
# N_train: 1000
# N_test: 100
seed: 42
solve: True
noise_std_dev: 0.0
